// <auto-generated />

using LudoLibrary.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace LudoLibrary.Migrations
{
    [DbContext(typeof(LudoContext))]
    internal class LudoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ludo.Entities.Comment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Content");

                b.Property<string>("Name");

                b.HasKey("Id");

                b.ToTable("Comments");
            });

            modelBuilder.Entity("Ludo.Entities.Rating", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Content");

                b.Property<int>("Stars");

                b.HasKey("Id");

                b.ToTable("Ratings");
            });

            modelBuilder.Entity("Ludo.Entities.Room", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name");

                b.HasKey("Id");

                b.ToTable("Rooms");
            });

            modelBuilder.Entity("Ludo.Entities.Score", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name");

                b.Property<int>("Points");

                b.HasKey("Id");

                b.ToTable("Scores");
            });

            modelBuilder.Entity("Ludo.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name");

                b.Property<int?>("RoomId");

                b.HasKey("Id");

                b.HasIndex("RoomId");

                b.ToTable("Users");
            });

            modelBuilder.Entity("Ludo.Entities.User", b =>
            {
                b.HasOne("Ludo.Entities.Room")
                    .WithMany("Users")
                    .HasForeignKey("RoomId");
            });
#pragma warning restore 612, 618
        }
    }
}